import "./index.css";
import { Composition } from "remotion";
import { MyComposition } from "./Composition";
import { AzoraAd } from "./AzoraAd";
import { FacebookAd } from "./FacebookAd";
import { FacebookAd16x9 } from "./FacebookAd16x9";
import { FacebookAd2, FacebookAd2_1x1, FacebookAd2_16x9 } from "./FacebookAd2";
import { BearGiftAd, BearGiftAd_4x5, BearGiftAd_1x1, BearGiftAd_16x9 } from "./BearGiftAd";
import {
  UrsuletTrandafirEternAd,
  UrsuletTrandafirEternAd_4x5,
  UrsuletTrandafirEternAd_1x1,
  UrsuletTrandafirEternAd_16x9,
} from "./UrsuletTrandafirEternAd";
import {
  ModelareCorporalaAd,
  ModelareCorporalaAd_4x5,
  ModelareCorporalaAd_1x1,
  ModelareCorporalaAd_16x9,
} from "./ModelareCorporalaAd";

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="MyComp"
        component={MyComposition}
        durationInFrames={60}
        fps={30}
        width={1280}
        height={720}
      />
      <Composition
        id="AzoraAd"
        component={AzoraAd}
        durationInFrames={620}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="FacebookAd-9x16"
        component={FacebookAd}
        durationInFrames={950}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="FacebookAd-4x5"
        component={FacebookAd}
        durationInFrames={950}
        fps={30}
        width={1080}
        height={1350}
      />
      <Composition
        id="FacebookAd-1x1"
        component={FacebookAd}
        durationInFrames={950}
        fps={30}
        width={1080}
        height={1080}
      />
      <Composition
        id="FacebookAd-16x9"
        component={FacebookAd16x9}
        durationInFrames={950}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="FacebookAd2-9x16"
        component={FacebookAd2}
        durationInFrames={1055}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="FacebookAd2-4x5"
        component={FacebookAd2}
        durationInFrames={1055}
        fps={30}
        width={1080}
        height={1350}
      />
      <Composition
        id="FacebookAd2-1x1"
        component={FacebookAd2_1x1}
        durationInFrames={1055}
        fps={30}
        width={1080}
        height={1080}
      />
      <Composition
        id="FacebookAd2-16x9"
        component={FacebookAd2_16x9}
        durationInFrames={1055}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="UrsuletTrandafirEternAd-4x5"
        component={UrsuletTrandafirEternAd_4x5}
        durationInFrames={660}
        fps={30}
        width={1080}
        height={1350}
      />
      <Composition
        id="UrsuletTrandafirEternAd-9x16"
        component={UrsuletTrandafirEternAd}
        durationInFrames={660}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="UrsuletTrandafirEternAd-1x1"
        component={UrsuletTrandafirEternAd_1x1}
        durationInFrames={660}
        fps={30}
        width={1080}
        height={1080}
      />
      <Composition
        id="UrsuletTrandafirEternAd-16x9"
        component={UrsuletTrandafirEternAd_16x9}
        durationInFrames={660}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="BearGiftAd-4x5"
        component={BearGiftAd_4x5}
        durationInFrames={900}
        fps={30}
        width={1080}
        height={1350}
      />
      <Composition
        id="BearGiftAd-9x16"
        component={BearGiftAd}
        durationInFrames={900}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BearGiftAd-1x1"
        component={BearGiftAd_1x1}
        durationInFrames={900}
        fps={30}
        width={1080}
        height={1080}
      />
      <Composition
        id="BearGiftAd-16x9"
        component={BearGiftAd_16x9}
        durationInFrames={900}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="ModelareCorporalaAd-4x5"
        component={ModelareCorporalaAd_4x5}
        durationInFrames={720}
        fps={30}
        width={1080}
        height={1350}
      />
      <Composition
        id="ModelareCorporalaAd-9x16"
        component={ModelareCorporalaAd}
        durationInFrames={720}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ModelareCorporalaAd-1x1"
        component={ModelareCorporalaAd_1x1}
        durationInFrames={720}
        fps={30}
        width={1080}
        height={1080}
      />
      <Composition
        id="ModelareCorporalaAd-16x9"
        component={ModelareCorporalaAd_16x9}
        durationInFrames={720}
        fps={30}
        width={1920}
        height={1080}
      />
    </>
  );
};
